### ISSUE TITLE
A problem in function set_platform_attribs

### ISSUE THREAD

**Issue by xuechiyaobai** [Coalfire-Research/iOS-11.1.2-15B202-Jailbreak#9]
Here is the snippet code:
`void set_platform_attribs(uint64_t proc, mach_port_t tfp0)
{
   ...
    uint64_t vnode_info = rk64(0x248);   `

I feel a bit confusion here "uint64_t vnode_info = rk64(0x248);"

**Comment by xuechiyaobai** [comment]
It seems like the JB will success although the |set_platform_attribs| runs not well.

**Comment by sierrahaex** [comment]
Correct.  That code is the result of coding too late at night ;) It does not work, but due to the error handling doesn't impact the jailbreak.  The code that you should actually care about is here:

`uint64_t task = rk64(proc+0x18);`
`uint64_t platform_addr = task + 0x3a0;`
`uint32_t platform = rk32(platform_addr);`
`wk32(platform_addr, platform | 0x400);`
`wk32(proc+0x279+0x2f, 0x24004001);`

**Comment by sierrahaex** [comment]
I've removed the code as of commit 2bca16e260cea87dd3323f47338fc6fd84c1bcd7

**Comment by xuechiyaobai** [comment]
Yes, it is.Thank you for your asking.
